<a href="https://colab.research.google.com/github/subhramannil/MY_LEARNING/blob/main/NN_MODULE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn


class Model(nn.Module): #Why are we doing it? because, we want to access the nn modules,

  def __init__(self,num_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [4]:
# Create dataset

features = torch.rand(10,5)

#Create a Model

model = Model(features.shape[1])

#Forward pass

model(features)

tensor([[0.5772],
        [0.6281],
        [0.5329],
        [0.5119],
        [0.5605],
        [0.6148],
        [0.5517],
        [0.4590],
        [0.5183],
        [0.6422]], grad_fn=<SigmoidBackward0>)

In [5]:
# model weights

model.linear.bias

Parameter containing:
tensor([-0.0196], requires_grad=True)

In [6]:
model.linear.weight

Parameter containing:
tensor([[-0.3595,  0.0559, -0.0154,  0.3917,  0.4171]], requires_grad=True)

In [7]:
! pip install torchinfo

In [8]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00