In [5]:
import scipy
#print(scipy.__version__)

from scipy import constants
print(constants.pi)
print(constants.atm)
print(constants.ounce)
print(constants.g)

3.141592653589793
101325.0
0.028349523124999998
9.80665


In [6]:
a = [1,2,3,4]
b = [4,5,6,7]

result = []
for first,second in zip(a,b):
    result.append(first+second)
result

[5, 7, 9, 11]

In [7]:
import numpy as np

In [8]:
a = np.array([1.2,3.2,22,1])
a.dtype

dtype('float64')

## NUMPY ARRAY SLICING

In [9]:
a = np.arange(25).reshape(5,5)

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
a[:,1::3]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24]])

In [12]:
a[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [13]:
a[4,:]

array([20, 21, 22, 23, 24])

In [14]:
a[-1,:]

array([20, 21, 22, 23, 24])

In [15]:
a = [1,2,3,4,5]

b = a[:2]

In [16]:
b

[1, 2]

In [17]:
b[0]=-1

In [18]:
b

[-1, 2]

In [19]:
a

[1, 2, 3, 4, 5]

In [20]:
a=np.array([1,2,3,4])
b=a[:2]
b[0]=-1
b

array([-1,  2])

In [21]:
a

array([-1,  2,  3,  4])

In [22]:
a[-2:] # Last 2 elements

array([3, 4])

## FANCY INDEXING

In [23]:
indices = [1,2,-4]

a = np.array([22,3,4,5,11,43,56])
y = a[indices]
y

array([3, 4, 5])

In [24]:
a[indices]=99

In [25]:
a

array([22, 99, 99, 99, 11, 43, 56])

In [26]:
a = np.arange(25).reshape(5,5)

In [27]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
for i in range(5):
    print(a[i,i])

0
6
12
18
24


In [39]:
a[[0],[2]]

array([2])

In [40]:
a[[0,1],[2,1]]

array([2, 6])

In [42]:
a[[0,1,-1],[2,1,-3]]

array([ 2,  6, 22])

In [43]:
a%3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]])

In [48]:
# numbers which are divisble by 3 in a
a%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [ ]:
a[a%3==0] #<---- we need True indexings

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [53]:
a = np.array([1,2,3]).reshape(1,3)
b = np.array([5,6,7]).reshape(3,1)
b

array([[5],
       [6],
       [7]])

In [50]:
a+b

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [51]:
a*b

array([[ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21]])

In [54]:
a = np.arange(16).reshape(4,4)

In [55]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
a.sum(axis = 0)

array([24, 28, 32, 36])

In [57]:
a.sum(axis = 1)

array([ 6, 22, 38, 54])

In [58]:
a.min(axis=0)

array([0, 1, 2, 3])

In [59]:
a.max()

np.int64(15)

In [60]:
a.max(axis=1)

array([ 3,  7, 11, 15])

In [63]:
a.argmax() # many tasks-> like optimisation , interested in location of min/max

np.int64(15)

In [64]:
np.argmin(a)

np.int64(0)

In [81]:
a = np.arange(-2,8,3)

In [82]:
a

array([-2,  1,  4,  7])

In [83]:
mask = a%2==0

In [84]:
np.where(mask)

(array([0, 2]),)

In [85]:
a == a.max()
a

array([-2,  1,  4,  7])

In [88]:
b = np.array([-2,1,4,7])
b == b.max()

array([False, False, False,  True])

In [ ]:
np.where(b==b.max()) # -- The expression b == b.max() returns a Boolean NumPy array (specifically an array with a dtype of bool).

(array([3]),)